# Generated by Django 6.0.3 on 2026-03-14 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_type', models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out'), ('adjustment', 'Adjustment'), ('transfer', 'Internal Transfer')], max_length=15)),
                ('quantity', models.IntegerField()),
                ('reference', models.CharField(blank=True, max_length=50)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('stock_before', models.IntegerField()),
                ('stock_after', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_moves', to='products.location')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='products.product')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_moves', to='products.location')),
            ],
            options={
                'verbose_name': 'Stock Ledger Entry',
                'verbose_name_plural': 'Stock Ledger',
                'ordering': ['-created_at'],
            },
        ),
    ]
